### ISSUE TITLE
Canasta should verify dependencies before doing anything

### ISSUE THREAD

**Issue by hexmode** [CanastaWiki/Canasta-Go#12]
The cli should verify that docker-compose, etc are available when it is invoked with any command that will use them.

For instance: `canasta help` does not require any external tools and it should (continue to) just work.

However `canasta create` does require the installation of [docker-compose](https://docs.docker.com/compose/) and it should refuse to run if it cannot find it.  Otherwise, you end up with this sort of frustrating dialog:
```
$ sudo ./canasta create
Enter Wiki Name: Test
Enter Canasta ID: test
Enter admin name: WikiSysop
Enter the admin password (Press Enter to autogenerate the password): 
Setting up Canasta
exec: "docker-compose": executable file not found in $PATH
$

**Comment by jeffw16** [comment]
@amalpaul54111 Please take a look at this
