### ISSUE TITLE
When canasta has failed, but created directories for an install, it can't run again against the same `create` without error

### ISSUE THREAD

**Issue by hexmode** [CanastaWiki/Canasta-Go#14]
Example:
```
$ ls -l test
total 24
drwxr-xr-x. 3 root root   86 Aug 19 01:15 config
-rw-r--r--. 1 root root  545 Aug 19 01:15 docker-compose.override.yml
...
$ sudo ./Canasta-CLI-Go create
Enter Wiki Name: test
Enter Canasta ID: test
Enter admin name: test
Enter the admin password (Press Enter to autogenerate the password): 
Setting up Canasta
fatal: destination path '/home/mah/Canasta-CLI/test' already exists and is not an empty directory.
$

**Comment by jeffw16** [comment]
@amalpaul54111 Please take a look at this

**Comment by amalpaul54111** [comment]
Yeah, that's right, now it does not remove the directories created during an installation when it fails. I guess an easy solution would be to delete the directories once an installation fails. Should that be its behavior?

**Comment by hexmode** [comment]
If it just created the directory and set up fails, the default behavior should be to delete it.  There should be an option to keep the directory, though, in case someone wants to debug what is the problem.

**Comment by amalpaul54111** [comment]
Yeah, sure. I will work on that.
