### ISSUE TITLE
Documentation for Restic commands

### ISSUE THREAD

**Issue by amalpaul54111** [CanastaWiki/Canasta-Go#22]

**Comment by amalpaul54111** [comment]
Should this be on a separate file or just on the main README.md.

**Comment by yaronkoren** [comment]
The main README, I would say - just as with the "extension" and "skin" commands.

**Comment by amalpaul54111** [comment]
Yeah, okay.

**Comment by amalpaul54111** [comment]
Would be added to the [Canasta Documentation](https://github.com/CanastaWiki/Canasta-Documentation) soon.
