### ISSUE TITLE
"canasta enable extension/skin" needs to output wfLoad instead of cfLoad

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta-Go#30]
The files /cmd/extension/extension.go and /cmd/skin/skin.go both need updating.

**Comment by olsonjaredm** [comment]
Also fix the cf in the included `config/settings/Vector.php` file.

**Comment by jeffw16** [comment]
By the way @olsonjaredm, I think your requested change was already made a few weeks ago, but feel free to correct me if I'm not talking about the same thing as you: https://github.com/CanastaWiki/Canasta-DockerCompose/commit/5001480aa63a81518240756b6722d4db592d8209

**Comment by olsonjaredm** [comment]
Perfect, looks great - I'll pull the latest.
