### ISSUE TITLE
Add commands to recreate extensions/, skins/ directories

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta-Go#39]
Now that the extensions/ and skins/ directories are automatically generated, it's sometimes necessary to recreate these directories - say, if the admin adds another extension to the user-extensions/ directory. It would be useful to have one or two CLI commands to recreate these directories as needed. I think two commands would be better, one for extensions and one for skins - like "canasta extension reload" and "canasta skin reload". Other possible command names for this are "refresh", "recreate" and "update" - I'm not sure which is best, though at the moment I'm leaning toward "reload".

**Comment by gitmapd** [comment]
Hello, "recreate" is a better term if those directories don't exist.

**Comment by jeffw16** [comment]
"recreate" is what's happening in the background, but "reload" is a good abstraction that's perfect to give the idea for the user of what its purpose is.

I support "reload" and oppose "recreate".

**Comment by yaronkoren** [comment]
This might no longer be necessary if the following is done:

- https://github.com/CanastaWiki/Canasta/issues/159

**Comment by yaronkoren** [comment]
Now that inotifywait is planned to be used to automatically update the symlinks, I don't think this command is necesary any more - I'm closing this issue.
