### ISSUE TITLE
Automatically-generated passwords don't show up anywhere?

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta-Go#40]
If you get an automatically-generated password for the admin account by leaving out the "-p" flag in "canasta create", the password that's generated doesn't seem to appear anywhere - so as far as I know it's lost forever. (If it does get stored somewhere, it would be good to know where - so that this can be noted in the documentation, and probably the CLI output as well.)

**Comment by amalpaul54111** [comment]
The automatically-generated password for the admin account is currently not accessible anywhere. The only way to access them is if one opt to use verbose mode when running the create command. It does print out the password when running the “maintenance/install.php” as an argument.

What would be a better option, just to print it on the terminal or to save it into a file?

**Comment by yaronkoren** [comment]
Good to know that this is indeed the case. I think saving it to a file is better - since the user could easily miss the output of the command when it's run. I don't know if any of the current configuration files make sense as a home for this password - if not, I'd suggest putting it in a new file, maybe called ".admin-password". If anyone wants a different name (or different approach), feel free to chime in.

By the way, what do you mean by “maintenance/install.php” as an argument? What would the full command look like?

**Comment by amalpaul54111** [comment]
Yeah, saving it in a file seems good.

The CLI use the "maintenance/install.php" to setup the Wiki. The full command would look like
```
php maintenance/install.php --dbserver=db  --confpath=/mediawiki/config/ --scriptpath=/w	--server='https://localhost' --dbuser='root' --dbpass='mysql' --pass='wikipassword' 'My Wiki' 'admin'
```
https://www.mediawiki.org/wiki/Manual:Install.php .

**Comment by yaronkoren** [comment]
Oh, now I understand what you mean - the password is the argument.

**Comment by freephile** [comment]
Is this documented? Where should the feature be documented?

If you choose to have Canasta generate an admin password for you, you will find it in a file named .admin-password

**Comment by amalpaul54111** [comment]
Its not documented yet. It could be documented at [Canasta-Documentation](https://github.com/CanastaWiki/Canasta-Documentation)/setup.md

> If you choose to have Canasta generate an admin password for you, you will find it in a file named .admin-password

Yes, you are right.
