### ISSUE TITLE
Create .config directory if it's needed and doesn't exist

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta-Go#42]
The function init() in config.go calls the function getConfigDir(), which in turn looks for the directory `.config/canasta` - and this call seems to always fail (and display an error message), because the directory doesn't exist.

It appears that all of this code was added in this patch, which was committed about two weeks ago:

https://github.com/CanastaWiki/Canasta-CLI/pull/13/files

@hexmode - can you explain what is going on with this code? Should the directory be getting created at some point? Or should this part of the code just be removed?

**Comment by hexmode** [comment]
I did confirm just now that the `.config/canasta` directory is not created if the `.config` directory does not exist.  If the `.config` directory does exist (as per [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.8.html) and implemented in [configdir](https://pkg.go.dev/github.com/kirsle/configdir)), the directory would be created.

The code obviously assumes that `.config` exists, but it should create it if it does not exist (which results in this bug).

If you are running canasta as root, it should (still) use `/etc/canasta`.

**Comment by amalpaul54111** [comment]
Should the CLI create the '.config' folder for the non-root user if it does not exist.

**Comment by yaronkoren** [comment]
Yes, I think so - otherwise every command will (I think) look for that directory, not find it, and display an error message.

**Comment by amalpaul54111** [comment]
Yeah, sure
