### ISSUE TITLE
Need CLI command to call any MW "maintenance" script

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta-Go#43]
It would be great to have a command that simply calls any script in the core MW maintenance/ directory - and lets you pass any parameters directly to that script - so that you don't have to go into the Docker container just to call, say, runJobs.php.

I know there's already a command called "canasta maintenance", so this would need a different name than that - what about "canasta maintenance script"? If that were done, perhaps the command now at "canasta maintenance" would be better made a subcommand too, like "canasta maintenance update" - which, looking at the code, is already kind of the name of this command anyway...

**Comment by gitmapd** [comment]
Hello, why not keep the "maintenance" as  main caller and why not add a sub-command or a flag.
Example:
canasta maintenance "script name"
canasta maintenance -s "script name"

**Comment by yaronkoren** [comment]
The latter option (with the "-s") is more or less what I'm recommending, just with a different flag name - "script" instead of "-s".
