### ISSUE TITLE
Remove automatically-added wfLoadSkin() calls from LocalSettings.php

### ISSUE THREAD

**Issue by hexmode** [CanastaWiki/Canasta-Go#85]
While moving wikiapiary, we noticed all the enabled skins were enabled in the embedded LocalSettings.php and could not (easily) be disabled.  The embedded LocalSettings should include as little customization possible and, where possible, it should be modifiable.

**Comment by jeffw16** [comment]
I know what's going on here. On startup, Canasta symlinks all of our bundled skins to the skins directory that MediaWiki sees. MediaWiki Core sees these directories and its install.php script auto-generates these lines.

**Comment by jeffw16** [comment]
We're already using the settings directory to enable Vector by default. We should probably add something in the CLI to remove these lines from LS after the installation completes. This bug doesn't apply to manual installs of MediaWiki on Canasta that don't use CLIs.

**Comment by yaronkoren** [comment]
I just renamed the issue - hopefully this accurately sums it up.
