### ISSUE TITLE
Canasta CLI now unusable on Ubuntu due to "docker compose" requirement?

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta-Go#87]
PR #78, if I understand it correctly, made the presence of "docker compose" (as opposed to "docker-compose") required to run the Canasta CLI. Which in theory is correct behavior, since "docker-compose" is the "v1", and now deprecated, while "docker compose" is the "v2". So that's good - but the problem is that, on Ubuntu, it seems like only "docker-compose" is installable. Which, if true, is a big problem.

The official Docker install guide for Ubuntu (https://docs.docker.com/engine/install/ubuntu/) says to call this:
```
 sudo apt-get update
 sudo apt-get install docker-compose-plugin
```
But when I do that (on a server running Ubuntu 20.0.4), I get the following message:
```
E: Unable to locate package docker-compose-plugin
```
Pretty shocking that the official instructions don't work. As might be expected, other people have noticed this problem; here is [one example](https://askubuntu.com/questions/1424118/how-to-install-docker-and-docker-compose-on-ubutntu-22-04) of someone giving alternate instructions. However, the instructions there don't work for me either (and they're more complicated).

This seems quite bad - and perhaps the only solution, for now, is to get the Canasta CLI to fully support both "docker-compose" and "docker compose".

**Comment by PiyushRaj927** [comment]
Hi @yaronkoren,

Have you added the apt repository for Docker as instructed in https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository? If so, `apt-get` should be able to locate them, as the `docker-compose-plugin` is available at https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/.

**Comment by yaronkoren** [comment]
@PiyushRaj927 - maybe that's the issue; I was trying to install the CLI on a server that already had Docker installed. Should Docker be un-installed, then installed the right way? And if so, maybe the CLI documentation should explain this?

**Comment by PiyushRaj927** [comment]
https://docs.docker.com/engine/install/ubuntu/#delete-old-versions indicates that builds offered by distros are unofficial, so I think it is best to uninstall the packages and install them from the official docker apt repo, to prevent version conflict when upgrading.

**Comment by freephile** [comment]
This issue, when fixed, should resolve #21, #59, #35

**Comment by freephile** [comment]
I brought up these related issues at the last meeting and will now work to fix them.

**Comment by freephile** [comment]
For **Desktop users** (Windows, Mac and Linux), I believe Canasta should drop support for the v1 binary `docker-compose`; emphasizing that the way to prepare your system for Canasta so that it has all prerequisites and works properly is to install **Docker Desktop** (which will have the correct and latest docker compose). 

For **System Administrators**, when existing systems may still rely on old tools or software that uses the deprecated `docker-compose`, we _could_ suggest the compatibility shim [Compose Switch](https://github.com/docker/compose-switch). Although, AFAIK, it is only good for Ubuntu and CentOS
