### ISSUE TITLE
mkdir /etc/canasta: permission denied

### ISSUE THREAD

**Issue by lexsulzer** [CanastaWiki/Canasta-Go#9]
https://github.com/CanastaWiki/Canasta-CLI-Go/blob/f9a334ba9e525ea4283cdf118d86682dd32cbd24/internal/logging/logging.go#L121

On Linux, when following the README.md instructions I get `mkdir /etc/canasta: permission denied`. Shouldn't logging use a folder in `/var/log/`?

**Comment by amalpaul54111** [comment]
Sorry for the confusion, here logging doesn't actually log the outputs to any file, its it mainly used to print the verbose output, and to read and write configuration files saved in the /etc/canasta/conf.json by default.

**Comment by amalpaul54111** [comment]
As of now, to run almost any canasta commands, one would have to use sudo or have permission to write to the configuration file.

**Comment by lexsulzer** [comment]
canasta shall always be run as sudo.

**Comment by hexmode** [comment]
See #12 and the fix in #13.

> canasta shall always be run as sudo.

I would hesitate to make such a demand when it is not needed.  See [rootless docker](https://docs.docker.com/engine/security/rootless/) or [podman + docker-compose](https://www.redhat.com/sysadmin/podman-docker-compose).

Containers are even better when you can keep them contained without root privileges.

**Comment by hexmode** [comment]
> > canasta shall always be run as sudo.
> 
> I would hesitate to make such a demand when it is not needed. See [rootless docker](https://docs.docker.com/engine/security/rootless/) or [podman + docker-compose](https://www.redhat.com/sysadmin/podman-docker-compose).

If a resource owner does not want to allow users without root privileges to run containers, then they should not allow non-root users to run containers -- that is a policy that a system administrator can implement.

If a resource owner has decided to allow users to run containers without sudo, though, Canasta should not require sudo.
